upstream agents {
    server agent_1:3050;
    server agent_2:3050;
}

server {
    listen 80;
    
    include /etc/nginx/mime.types;

    location / {
        proxy_pass http://agents/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
